name: QEventBox
version: '1.0'
main: me.bintanq.qEventBox.QEventBox
api-version: '1.21'
authors: [ bintanq ]
description: Spawn box for Prizes
commands:
  qeventbox:
    description: Main admin command to control crate drops & reload
    usage: /qeventbox <spawnauto|spawn|remove|status|reload>
    permission: qeventbox.admin
    aliases: [qeb, eventbox]
  eventshop:
    description: Open event shop GUI
    usage: /eventshop
    permission: qeventbox.
    aliases: [qshop, eshop]
  qpoints:
    description: Manage player event points
    usage: /qpoints <check|give|remove|set> <player> [amount]
    permission: qeventbox.admin
    aliases: [qp]
permissions:
  qeventbox.admin:
    default: op
  qeventbox.shop:
    default: true